### ISSUE TITLE
v1.6.0 removes attribute_map class method from model

### ISSUE THREAD

**Issue by JasonPoll** [apokalipto/devise_saml_authenticatable#178]
Upgrading from v1.5.0 to v1.6.0 introduces a breaking change (#162) for use cases that utilize the `attribute_map` class method that's extended onto the target model (`User` in my situation.) 

v1.5.0:
``` ruby
User.attribute_map
=> {"a" => "b", "c" => "d"}
```

v1.6.0:
``` ruby
User.attribute_map
=> NoMethodError: undefined method `attribute_map'...
```

I realize the change introduced in #162 is for the better and I intended to put it to use when/if my application needs to support multiple IdPs, however I didn't notice this breaking change noted in the README.md. My next inclination was to look for a changelog, but couldn't find one. 

Until such time that I need to support multiple IdPs in my application and wish to continue accessing my attribute mapping through Devise, am I correct that this is an acceptable way to access my `attribute-map.yml`? 

``` ruby
Devise.aml_attribute_map_resolver.new(nil).attribute_map
=> {"a" => "b", "c" => "d"}
```

I realize I could also load my `attribute-map.yml` directly, or implement my own `DeviseSamlAuthenticatable::DefaultAttributeMapResolver` derivation, but am looking for confirmation on a quick-fix while we plan and prioritize implementing a proper attribute map resolver.

**Comment by adamstegman** [comment]
Oh no! Thank you for bringing this up, and sorry for the inconvenience. Your example should work fine. I'll work on a 1.6.1 to put that method back as well.

**Comment by JasonPoll** [comment]
Thank you for the quick response! Looking at #179, your refactor to reintroduce the attribute_map method looks good to me!

**Comment by adamstegman** [comment]
Just released 1.6.1 to replace this method.
